### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by Nadimkhan120** [Mindinventory/react-native-boilerplate#35]
Hello
This is a very great template to start a new project in react native, but i think now a days using expo is very great, expo has tons of great features. My question is that do you guys have any plans to support expo?

**Comment by akashmi** [comment]
@Nadimkhan120 Thanks for your inputs.
And yes, team is currently working on expo support. we are planning to release new version soon with expo support.

**Comment by akashmi** [comment]
Expo support has been introduced in version `v3.0.0`.
```
npx @mindinventory/react-native-boilerplate
```
Check readme for the more details.
