### ISSUE TITLE
env URL not accepting when axios API call happening...

### ISSUE THREAD

**Issue by commencementtech** [Mindinventory/react-native-boilerplate#36]
![image](https://github.com/user-attachments/assets/4fec9a2a-6c3f-4663-86b2-a4b929b38db5)
![image](https://github.com/user-attachments/assets/05f8c427-f777-4a40-9978-34f234ea59ff)

From where can I set this API_URL in the code, as it's not found anywhere in the system?

**Comment by ankitpmi** [comment]
Hi @commencementtech.
Thank you for raising this issue and for your patience. I understand the confusion regarding where to set the `API_URL` for Axios calls. Here's how you'd be able to resolve this...

We have used [react-native-config](https://www.npmjs.com/package/react-native-config) package for managing environment variables to the app.

You can set your environment variables (`API_URL`, `ENV`) in the `.env` file. Also, you can add more variables there.

Please take a look at our documentation for more details [(here)](https://mindinventory.github.io/react-native-boilerplate/docs/configuration/environment-setup/).
