### ISSUE TITLE
[ERROR] Initializing project error

### ISSUE THREAD

**Issue by arnimi** [Mindinventory/react-native-boilerplate#38]
error An unexpected error occurred: Command failed with EACCES: /tmp/rncli-init-template-4xv73R/node_modules/@mindinventory/react-native-boilerplate/script.js
spawn /tmp/rncli-init-template-4xv73R/node_modules/@mindinventory/react-native-boilerplate/script.js EACCES.

**Comment by sikky999** [comment]
yes same issue

**Comment by chiragramimi** [comment]
@arnimi @sikky999 Thank you for reporting this issue. This error is likely caused by insufficient terminal permissions, often due to the lack of sudo access, you can try running the command with sudo to see if it resolves the issue.

**Comment by ankitpmi** [comment]
Hello @arnimi and @sikky999 
We have resolved this issue and published a new version. So please try out the latest version and let us know if you still have the same issue.

Thanks.

**Comment by ankitpmi** [comment]
Hello @arnimi and @sikky999  
We have resolved this issue and published a new version. So please try out the latest version and let us know if you still have the same issue.

Thanks.

**Comment by khaasaadmi** [comment]
$ npx pod-install
⚠️ CocoaPods is only supported on darwin machines
$ husky
Done in 189.49s.
Dependencies installed successfully. 🚀

bundle Installing 🛠️

'bundle' is not recognized as an internal or external command,
operable program or batch file.
🚨 An error occurred with post init script: Error: Command failed: bundle
C:\Users\ojasg\AppData\Local\Temp\rncli-init-template-zYlKc0\node_modules\@mindinventory\react-native-boilerplate\script.js:58
    throw new Error()
          ^

Error
    at C:\Users\ojasg\AppData\Local\Temp\rncli-init-template-zYlKc0\node_modules\@mindinventory\react-native-boilerplate\script.js:58:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    reciveing this error and using node version 18 is it a problem if i do not use latest node ?
because after this error no yarn start , npm start command is also working

**Comment by chiragramimi** [comment]
> $ npx pod-install ⚠️ CocoaPods is only supported on darwin machines $ husky Done in 189.49s. Dependencies installed successfully. 🚀
> 
> bundle Installing 🛠️
> 
> 'bundle' is not recognized as an internal or external command, operable program or batch file. 🚨 An error occurred with post init script: Error: Command failed: bundle C:\Users\ojasg\AppData\Local\Temp\rncli-init-template-zYlKc0\node_modules@mindinventory\react-native-boilerplate\script.js:58 throw new Error() ^
> 
> Error at C:\Users\ojasg\AppData\Local\Temp\rncli-init-template-zYlKc0\node_modules@mindinventory\react-native-boilerplate\script.js:58:11 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) reciveing this error and using node version 18 is it a problem if i do not use latest node ? because after this error no yarn start , npm start command is also working

Hello @khaasaadmi,
Could you please share the following details related to your project setup?

Node Version:
Operating System Version:
xcode version:

Thank you!

**Comment by khaasaadmi** [comment]
My node version is
V 18.30.5
Windows 11
There is no xcode installed

**Comment by AlanDataPortfolio** [comment]
Just want to pop in:
Node: 20.18.1
OS: MacOS Sequoia 15.2
Xcode: 16.2

I ran: `npx @react-native-community/cli init APP_NAME --template @mindinventory/react-native-boilerplate` with and without sudo but this error keeps popping up:

==ERROR LOG==
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: yarn
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at installDependencies (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:15:3)
    at main (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:70:3)
    at /private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:75:3
    at new Promise (<anonymous>)
    at Object.<anonymous> (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:74:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 96449,
  stdout: null,
  stderr: null
}

Node.js v20.18.1

error An unexpected error occurred: Command failed with exit code 1: /tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js.

**Comment by Nkgohil007** [comment]
> Just want to pop in: Node: 20.18.1 OS: MacOS Sequoia 15.2 Xcode: 16.2
> 
> I ran: `npx @react-native-community/cli init APP_NAME --template @mindinventory/react-native-boilerplate` with and without sudo but this error keeps popping up:
> 
> ==ERROR LOG== node:internal/errors:984 const err = new Error(message); ^
> 
> Error: Command failed: yarn at genericNodeError (node:internal/errors:984:15) at wrappedFn (node:internal/errors:538:14) at checkExecSyncError (node:child_process:891:11) at execSync (node:child_process:963:15) at installDependencies (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:15:3) at main (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:70:3) at /private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:75:3 at new Promise () at Object. (/private/tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js:74:1) at Module._compile (node:internal/modules/cjs/loader:1469:14) { status: 127, signal: null, output: [ null, null, null ], pid: 96449, stdout: null, stderr: null }
> 
> Node.js v20.18.1
> 
> error An unexpected error occurred: Command failed with exit code 1: /tmp/rncli-init-template-UqKNK4/node_modules/@mindinventory/react-native-boilerplate/script.js.

Hello @AlanDataPortfolio 
You can check for the installation of yarn in your system globally.
```yarn -v```
If not installed then you can installed it by using the below command.
```npm install --global yarn```
After that you can run the below command to create boilerplate with our project.
```npx @react-native-community/cli init APP_NAME --template @mindinventory/react-native-boilerplate```
