### ISSUE TITLE
When the project starts, loading News prompts a network error

### ISSUE THREAD

**Issue by JessePinkman-JP** [Mindinventory/react-native-boilerplate#9]
First of all, this is a very good boilerplate. 
In the process of using it, I encountered some problems. First of all, as the title says, I don't know if the author can provide the following sample Api Server.
If you can't provide it, that's okay.
The second problem is that the README document says,
Put your images in the Images folder and run Images Script.
But... const {getImages} = useAppContext ();
The useAppContext here cannot get getImages. Is there anything I did wrong?
I hope the author can help me, thank you very much

**Comment by chiragramimi** [comment]
@JessePinkman-JP, 

Thank you for bringing this issue to our attention. We will be working on resolving it and will provide an update once the issue has been addressed.

**Comment by chiragramimi** [comment]
@JessePinkman-JP Thank you for addressing the issue and feedback. We've revised the readme for the image script, so kindly examine it and adhere to the specified steps. We'll incorporate this modification in npm 2.0.2.
